import { DeviceType } from './types';

export const DEVICE_CATALOG: DeviceType[] = [
  {
    id: 'mikrotik-rb5009',
    vendor: 'MikroTik',
    model: 'RB5009UG+S+',
    category: 'router',
    visual: { logicalSymbol: 'router' },
    capabilities: { osFamily: 'RouterOS', routing: true, switching: true, poeIn: true },
    interfaces: [
      { id: 'ether1', name: 'ether1 (2.5G)', media: 'rj45', maxSpeedMbps: 2500, poeIn: true },
      ...Array.from({ length: 7 }, (_, i) => ({
        id: `ether${i + 2}`, name: `ether${i + 2}`, media: 'rj45' as const, maxSpeedMbps: 1000,
      })),
      { id: 'sfp-sfpplus1', name: 'sfp-sfpplus1 (10G)', media: 'sfp+', maxSpeedMbps: 10000 },
    ],
  },
  {
    id: 'mikrotik-crs326',
    vendor: 'MikroTik',
    model: 'CRS326-24G-2S+',
    category: 'switch',
    visual: { logicalSymbol: 'switch' },
    capabilities: { osFamily: 'SwOS', routing: true, switching: true },
    interfaces: [
      ...Array.from({ length: 24 }, (_, i) => ({
        id: `ether${i + 1}`, name: `ether${i + 1}`, media: 'rj45' as const, maxSpeedMbps: 1000,
      })),
      { id: 'sfp-sfpplus1', name: 'sfp-sfpplus1 (10G)', media: 'sfp+', maxSpeedMbps: 10000 },
      { id: 'sfp-sfpplus2', name: 'sfp-sfpplus2 (10G)', media: 'sfp+', maxSpeedMbps: 10000 },
    ],
  },
  {
    id: 'ubiquiti-u6-pro',
    vendor: 'Ubiquiti',
    model: 'UniFi U6 Pro',
    category: 'access-point',
    visual: { logicalSymbol: 'access-point' },
    capabilities: { osFamily: 'UniFi OS', wifi: 'Wi-Fi 6', poeIn: true },
    interfaces: [{ id: 'eth0', name: 'GbE PoE uplink', media: 'rj45', maxSpeedMbps: 1000, poeIn: true }],
  },
  {
    id: 'generic-desktop',
    vendor: 'Generic',
    model: 'Desktop PC',
    category: 'desktop',
    visual: { logicalSymbol: 'desktop' },
    capabilities: { osFamily: 'Generic' },
    interfaces: [{ id: 'eth0', name: 'Ethernet 0', media: 'rj45', maxSpeedMbps: 1000 }],
  },
  {
    id: 'generic-server',
    vendor: 'Generic',
    model: 'Server',
    category: 'server',
    visual: { logicalSymbol: 'server' },
    capabilities: { osFamily: 'Generic' },
    interfaces: [
      { id: 'eth0', name: 'Ethernet 0', media: 'rj45', maxSpeedMbps: 1000 },
      { id: 'eth1', name: 'Ethernet 1', media: 'rj45', maxSpeedMbps: 1000 },
    ],
  },
  {
    id: 'generic-printer',
    vendor: 'Generic',
    model: 'Network Printer',
    category: 'printer',
    visual: { logicalSymbol: 'printer' },
    capabilities: { osFamily: 'Generic' },
    interfaces: [{ id: 'eth0', name: 'Ethernet 0', media: 'rj45', maxSpeedMbps: 1000 }],
  },
  {
    id: 'generic-camera',
    vendor: 'Generic',
    model: 'IP Camera',
    category: 'camera',
    visual: { logicalSymbol: 'camera' },
    capabilities: { osFamily: 'Generic', poeIn: true },
    interfaces: [{ id: 'eth0', name: 'PoE Ethernet', media: 'rj45', maxSpeedMbps: 1000, poeIn: true }],
  },
  {
    id: 'generic-nvr',
    vendor: 'Generic',
    model: 'NVR',
    category: 'nvr',
    visual: { logicalSymbol: 'nvr' },
    capabilities: { osFamily: 'Generic' },
    interfaces: [
      { id: 'lan0', name: 'LAN 0', media: 'rj45', maxSpeedMbps: 1000 },
      { id: 'lan1', name: 'LAN 1', media: 'rj45', maxSpeedMbps: 1000 },
    ],
  },
  {
    id: 'generic-internet',
    vendor: 'Generic',
    model: 'Internet Cloud',
    category: 'internet',
    visual: { logicalSymbol: 'internet' },
    capabilities: { osFamily: 'Generic' },
    interfaces: [{ id: 'wan0', name: 'WAN handoff', media: 'rj45', maxSpeedMbps: 10000 }],
  },
];
